# Enable flake8-bugbear (`B`) rules.
lint.select = ["E", "F", "B"]

# Never enforce `E501` (line length violations).
lint.ignore = ["E501"]

# Avoid trying to fix flake8-bugbear (`B`) violations.
lint.unfixable = ["B"]
